services:
  ft_nmap:
    build: ./vm
    init: true
    container_name: ft_nmap
    network_mode: "host"
    cap_add:
      - NET_ADMIN
    volumes:
      - ./code:/work
    working_dir: /work
    command: ["sleep", "infinity"]